pipeline:
  name: java_project
  identifier: java_project
  projectIdentifier: agents
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_tony
        repoName: java_project
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: tr...
          steps:
            - step:
                name: Run_5
                identifier: Run_5
                type: Run
                spec:
                  shell: Sh
                  command: |
                    set -e
                    pwd
                    ls
                    # cat dummy.txt
                    /tmp/harness-PjrXIEONSCm90DmNonZgkA
