pipeline:
  name: java_project
  identifier: java_project
  projectIdentifier: agents
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_tony
        repoName: java_project
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          steps:
            - step:
                type: Run
                name: secret_demo
                identifier: secret_demo
                spec:
                  shell: Sh
                  command: "echo \"DB URL is: <+secrets.getValue(\"DB_URL\")>\""
                  when:
                    stageStatus: Success
